apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container # ğŸ¯ Un nombre Ãºnico para el contenedor
      image: nginx:1.14.2  # ğŸ¯ La imagen de Docker a usar
      ports:
        - containerPort: 80 # ğŸ¯ El puerto que expone el contenedor